FROM php:{{ env.phpVersion }}-{{ env.distribution }}

LABEL org.opencontainers.image.source=https://github.com/espocrm/espocrm
LABEL org.opencontainers.image.description="EspoCRM is a free and open-source CRM platform."

# Persistent dependencies
RUN set -eux; \
	apk add --no-cache \
		bash \
	;

# Install PHP libs
RUN set -eux; \
    apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        postgresql-dev \
        libzip-dev \
        libpng-dev \
        libjpeg-turbo-dev \
        libwebp-dev \
        freetype-dev \
        openldap-dev \
        openssl-dev \
        libzmq \
        zeromq-dev \
    ; \
    \
    # Install php-zmq
        cd /usr; \
        curl -fSL https://github.com/zeromq/php-zmq/archive/616b6c64ffd3866ed038615494306dd464ab53fc.tar.gz -o php-zmq.tar.gz; \
        tar -zxf php-zmq.tar.gz; \
        cd php-zmq*; \
        phpize && ./configure; \
        make; \
        make install; \
        cd .. && rm -rf php-zmq*; \
    # END: Install php-zmq
    \
    pecl install \
        ev \
        redis \
    ; \
    \
    docker-php-ext-configure gd \
        --with-freetype \
        --with-jpeg=/usr/include \
        --with-webp \
    ; \
    \
    docker-php-ext-install -j "$(nproc)" \
        gd \
        pdo_pgsql \
        pdo_mysql \
        zip \
        ldap \
        exif \
        pcntl \
        bcmath \
    ; \
    docker-php-ext-enable \
        zmq \
        ev \
        redis \
    ; \
    rm -r /tmp/pear; \
    \
    runDeps="$( \
		scanelf --needed --nobanner --format '%n#p' --recursive /usr/local \
			| tr ',' '\n' \
			| sort -u \
			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
	)"; \
    apk add --no-network --virtual .espocrm-phpexts-rundeps $runDeps; \
	apk del --no-network .build-deps

# php.ini
RUN { \
    echo 'expose_php = Off'; \
    echo 'error_reporting = E_ALL & ~E_NOTICE & ~E_DEPRECATED'; \
    echo 'display_errors = Off'; \
    echo 'display_startup_errors = Off'; \
    echo 'log_errors = On'; \
    echo 'memory_limit=256M'; \
    echo 'max_execution_time=180'; \
    echo 'max_input_time=180'; \
    echo 'post_max_size=50M'; \
    echo 'upload_max_filesize=50M'; \
    echo 'date.timezone=UTC'; \
} > ${PHP_INI_DIR}/conf.d/espocrm.ini

ENV ESPOCRM_VERSION {{ .version }}
ENV ESPOCRM_SHA256 {{ .sha256 }}

WORKDIR /var/www/html

RUN set -eux; \
    curl -fSL "{{ .downloadUrl }}" -o EspoCRM.zip; \
    echo "${ESPOCRM_SHA256} *EspoCRM.zip" | sha256sum -c -; \
    unzip -q EspoCRM.zip -d /usr/src; \
    cp -a "/usr/src/EspoCRM-${ESPOCRM_VERSION}/." /var/www/html/; \
    rm -rf /usr/src/EspoCRM*; \
    mkdir -p /usr/src/espocrm; \
    cp -a ./client/ /usr/src/espocrm/; \
    cp -a ./public/ /usr/src/espocrm/; \
    rm -rf ./install; \
    find . -type d -exec chmod 755 {} +; \
    find . -type f -exec chmod 644 {} +; \
    chown -R root:root . /usr/src/espocrm; \
    chown -R www-data:www-data ./data ./custom ./client/custom; \
    chmod +x ./bin/command

COPY ./docker-*.sh ./entrypoint-utils.sh /usr/local/bin/

ENTRYPOINT [ "docker-entrypoint.sh" ]

CMD ["php-fpm"]
